from django.core.management.base import BaseCommand
from store.models import Category, Product


class Command(BaseCommand):
    help = 'Load initial products from static HTML files into database'

    def handle(self, *args, **kwargs):
        self.stdout.write('Loading products...')
        
        # Create categories
        categories_data = [
            {'name': 'Citrine', 'description': 'Beautiful citrine gemstones'},
            {'name': 'Quartz', 'description': 'Natural quartz varieties'},
            {'name': 'Opal', 'description': 'Ethiopian and natural opals'},
            {'name': 'Cabochon', 'description': 'Polished cabochon gemstones'},
            {'name': 'Moonstone', 'description': 'Rainbow moonstone collection'},
            {'name': 'Amethyst', 'description': 'Purple amethyst gemstones'},
            {'name': 'Sunstone', 'description': 'Oregon sunstone collection'},
            {'name': 'Others', 'description': 'Other rare gemstones'},
        ]
        
        categories = {}
        for cat_data in categories_data:
            category, created = Category.objects.get_or_create(
                name=cat_data['name'],
                defaults={'description': cat_data['description']}
            )
            categories[cat_data['name']] = category
            if created:
                self.stdout.write(self.style.SUCCESS(f'Created category: {category.name}'))
        
        # Create products based on the 20 static HTML files
        products_data = [
            {
                'name': 'AAA+ Citrine Faceted',
                'slug': 'citrine-faceted',
                'description': 'Known as the "stone of the mind", Citrine is a powerful cleanser and regenerator. This AAA+ grade faceted bead strand radiates a vibrant yellow hue, perfect for creating jewelry that inspires joy and abundance.',
                'price': 58.00,
                'image': 'https://i.etsystatic.com/27172493/r/il/5106a2/5127379095/il_1080xN.5127379095_iu5b.jpg',
                'stock': 15,
                'category': categories['Citrine'],
                'product_type': 'Bead Strand',
                'origin': 'Brazil',
                'size': '3mm - 5mm',
                'treatment': 'Heated',
                'is_featured': True,
            },
            {
                'name': 'Black Rutilated Quartz',
                'slug': 'black-rutilated-quartz',
                'description': 'Stunning black rutilated quartz with natural inclusions. Each piece is unique with beautiful needle-like rutile formations creating mesmerizing patterns within the crystal.',
                'price': 64.50,
                'image': 'https://i.etsystatic.com/7936415/r/il/c3f4ee/628217475/il_1080xN.628217475_3cp5.jpg',
                'stock': 12,
                'category': categories['Quartz'],
                'product_type': 'Faceted Beads',
                'origin': 'Brazil',
                'size': '4mm - 6mm',
                'treatment': 'Natural',
                'is_featured': True,
            },
            {
                'name': 'Natural Ethiopian Opal',
                'slug': 'natural-ethiopian-opal',
                'description': 'Spectacular Ethiopian opal displaying vibrant play-of-color. These natural opals show flashes of red, orange, green, and blue, making each piece truly unique.',
                'price': 49.99,
                'image': 'https://a.1stdibscdn.com/opal-stone-2567-carat-oval-natural-ethiopian-loose-gemstone-for-sale-picture-2/j_5693/1688930084714/mobilejpegupload_5A555835098241C18493219251F50D8C_master.jpg',
                'stock': 8,
                'category': categories['Opal'],
                'product_type': 'Loose Gemstone',
                'origin': 'Ethiopia',
                'size': '25.67 Carat',
                'treatment': 'Natural',
                'is_featured': True,
            },
            {
                'name': 'Silver Cat\'s Eye Cube',
                'slug': 'silver-cats-eye-cube',
                'description': 'Rare silver cat\'s eye gemstone in cube shape. Features the characteristic chatoyancy effect that creates a luminous band across the stone.',
                'price': 58.50,
                'image': 'https://th.bing.com/th/id/R.28db186ae2be896b28735c514045a278?rik=R%2bK3Sh8miEvmvw&riu=http%3a%2f%2falookaran.com%2fwp-content%2fuploads%2f2023%2f07%2fcats-eye.jpg&ehk=aQ6MA1f7BK3DJpuB0aCvh4BGzLveyHVPrwjaOpApUpg%3d&risl=&pid=ImgRaw&r=0',
                'stock': 10,
                'category': categories['Others'],
                'product_type': 'Cube Beads',
                'origin': 'India',
                'size': '6mm - 8mm',
                'treatment': 'Natural',
                'is_featured': True,
            },
            {
                'name': 'Peach Diamond Buzz',
                'slug': 'peach-diamond-buzz',
                'description': 'Delicate peach-colored diamond beads with natural sparkle. Perfect for creating elegant and sophisticated jewelry pieces.',
                'price': 47.00,
                'image': 'https://tse3.mm.bing.net/th/id/OIP.2bO8xVsxNHQ7qe0Rioa2QAHaFj?pid=Api&P=0&h=180',
                'stock': 20,
                'category': categories['Others'],
                'product_type': 'Diamond Beads',
                'origin': 'India',
                'size': '2mm - 3mm',
                'treatment': 'Natural',
            },
            {
                'name': 'Yellow Citrine',
                'slug': 'yellow-citrine',
                'description': 'Bright yellow citrine gemstones with excellent clarity. Known for attracting prosperity and success.',
                'price': 68.00,
                'image': 'https://zohari.in/wp-content/uploads/2022/05/61-WhYWNLFL._UL1000_.jpg',
                'stock': 18,
                'category': categories['Citrine'],
                'product_type': 'Faceted Beads',
                'origin': 'Brazil',
                'size': '5mm - 7mm',
                'treatment': 'Heated',
            },
            {
                'name': 'Oregon Round Faceted Sunstone',
                'slug': 'oregon-sunstone',
                'description': 'Premium Oregon sunstone with beautiful schiller effect. These rare gemstones display copper inclusions that create a stunning metallic sheen.',
                'price': 136.00,
                'image': 'https://tse1.explicit.bing.net/th/id/OIP.PfAGvMQT4kbkKWvFjMZeMQHaHa?cb=thfvnext&rs=1&pid=ImgDetMain&o=7&rm=3',
                'stock': 6,
                'category': categories['Sunstone'],
                'product_type': 'Faceted Round',
                'origin': 'Oregon, USA',
                'size': '6mm - 8mm',
                'treatment': 'Natural',
            },
            {
                'name': 'Natural Round Amethyst',
                'slug': 'natural-amethyst',
                'description': 'Deep purple amethyst beads with excellent color saturation. Known for its calming and protective properties.',
                'price': 25.50,
                'image': 'https://cdn.shopify.com/s/files/1/0825/7459/products/af30.1_large.jpg?v=1542901072',
                'stock': 25,
                'category': categories['Amethyst'],
                'product_type': 'Round Beads',
                'origin': 'Brazil',
                'size': '4mm - 6mm',
                'treatment': 'Natural',
            },
            {
                'name': 'Blue Turquoise Oval Cabochon',
                'slug': 'blue-turquoise-cabochon',
                'description': 'Beautiful blue turquoise cabochons with natural matrix patterns. Perfect for southwestern-style jewelry.',
                'price': 36.99,
                'image': 'https://thegemsfacet.com/wp-content/uploads/2025/01/il_1588xN.1588857242_spdl.webp',
                'stock': 14,
                'category': categories['Cabochon'],
                'product_type': 'Oval Cabochon',
                'origin': 'Arizona, USA',
                'size': '10mm x 14mm',
                'treatment': 'Stabilized',
            },
            {
                'name': 'Black Oval Cabochon',
                'slug': 'black-oval-cabochon',
                'description': 'Sleek black gemstone cabochons with high polish. Versatile for modern and classic jewelry designs.',
                'price': 50.99,
                'image': 'https://thegemsfacet.com/wp-content/uploads/2025/01/il_1588xN.1309965248_9jgr.webp',
                'stock': 16,
                'category': categories['Cabochon'],
                'product_type': 'Oval Cabochon',
                'origin': 'India',
                'size': '12mm x 16mm',
                'treatment': 'Natural',
            },
            {
                'name': 'Natural Rainbow Moonstone',
                'slug': 'rainbow-moonstone',
                'description': 'Ethereal rainbow moonstone with blue flash adularescence. Highly sought after for its mystical appearance.',
                'price': 36.99,
                'image': 'https://thegemsfacet.com/wp-content/uploads/2024/12/il_1588xN.2112552636_j9z6.webp',
                'stock': 11,
                'category': categories['Moonstone'],
                'product_type': 'Faceted Beads',
                'origin': 'India',
                'size': '5mm - 7mm',
                'treatment': 'Natural',
            },
            {
                'name': 'Natural Citrine Gemstone',
                'slug': 'natural-citrine-gemstone',
                'description': 'Genuine natural citrine with warm golden tones. Unheated and untreated for maximum authenticity.',
                'price': 32.00,
                'image': 'https://thegemsfacet.com/wp-content/uploads/2024/11/il_1588xN.2014925251_s4ty.webp',
                'stock': 13,
                'category': categories['Citrine'],
                'product_type': 'Faceted Beads',
                'origin': 'Brazil',
                'size': '4mm - 5mm',
                'treatment': 'Natural',
            },
            {
                'name': 'Boulder Opal',
                'slug': 'boulder-opal',
                'description': 'Unique boulder opal with natural ironstone backing. Features vibrant color play against dark matrix.',
                'price': 36.99,
                'image': 'https://thegemsfacet.com/wp-content/uploads/2024/11/il_1588xN.2911060498_6try.webp',
                'stock': 7,
                'category': categories['Opal'],
                'product_type': 'Loose Gemstone',
                'origin': 'Australia',
                'size': 'Various',
                'treatment': 'Natural',
            },
            {
                'name': 'Black Rutilated Quartz Premium',
                'slug': 'black-rutilated-quartz-premium',
                'description': 'Premium grade black rutilated quartz with dense needle inclusions. Museum quality specimens.',
                'price': 69.99,
                'image': 'https://thegemsfacet.com/wp-content/uploads/2024/10/il_1588xN.1665993091_lsim-768x768.webp',
                'stock': 5,
                'category': categories['Quartz'],
                'product_type': 'Faceted Beads',
                'origin': 'Brazil',
                'size': '6mm - 8mm',
                'treatment': 'Natural',
            },
            {
                'name': 'Grandidierite Gemstone',
                'slug': 'grandidierite-gemstone',
                'description': 'Extremely rare grandidierite gemstone. One of the world\'s rarest minerals with stunning blue-green color.',
                'price': 149.99,
                'image': 'https://thegemsfacet.com/wp-content/uploads/2024/10/il_1588xN.2119084013_bry8.webp',
                'stock': 3,
                'category': categories['Others'],
                'product_type': 'Faceted',
                'origin': 'Madagascar',
                'size': '3mm - 4mm',
                'treatment': 'Natural',
            },
            {
                'name': 'Pink Opal Oval Cabochon',
                'slug': 'pink-opal-cabochon',
                'description': 'Soft pink opal cabochons with smooth finish. Perfect for feminine and delicate jewelry designs.',
                'price': 36.99,
                'image': 'https://thegemsfacet.com/wp-content/uploads/2024/09/il_1588xN.1938890194_hwu9.jpg',
                'stock': 19,
                'category': categories['Cabochon'],
                'product_type': 'Oval Cabochon',
                'origin': 'Peru',
                'size': '10mm x 12mm',
                'treatment': 'Natural',
            },
            {
                'name': 'Natural Lapis Lazuli Gemstone',
                'slug': 'lapis-lazuli',
                'description': 'Deep blue lapis lazuli with golden pyrite inclusions. Prized since ancient times for its royal blue color.',
                'price': 174.99,
                'image': 'https://thegemsfacet.com/wp-content/uploads/2024/08/il_794xN.1668755922_edt3.jpg',
                'stock': 9,
                'category': categories['Others'],
                'product_type': 'Faceted Beads',
                'origin': 'Afghanistan',
                'size': '6mm - 8mm',
                'treatment': 'Natural',
            },
            {
                'name': 'Natural Opalina Gemstone',
                'slug': 'opalina-gemstone',
                'description': 'Translucent opalina with subtle color play. Also known as common opal, perfect for everyday jewelry.',
                'price': 67.00,
                'image': 'https://thegemsfacet.com/wp-content/uploads/2024/07/il_1588xN.2706292810_mnrx.jpg',
                'stock': 12,
                'category': categories['Opal'],
                'product_type': 'Beads',
                'origin': 'Mexico',
                'size': '5mm - 7mm',
                'treatment': 'Natural',
            },
            {
                'name': 'Ethiopian Welo Opal Gemstone',
                'slug': 'ethiopian-welo-opal',
                'description': 'Premium Welo opal from Ethiopia with exceptional play-of-color. Shows full spectrum of colors in natural light.',
                'price': 99.99,
                'image': 'https://thegemsfacet.com/wp-content/uploads/2024/01/il_1588xN.3025615330_54d1.jpg',
                'stock': 6,
                'category': categories['Opal'],
                'product_type': 'Faceted',
                'origin': 'Ethiopia',
                'size': '4mm - 6mm',
                'treatment': 'Natural',
            },
            {
                'name': 'Natural Labradorite Loose Gemstone Cube',
                'slug': 'labradorite-cube',
                'description': 'Mystical labradorite cubes with strong blue and green flash. Known for its protective and transformative properties.',
                'price': 25.00,
                'image': 'https://thegemsfacet.com/wp-content/uploads/2023/12/il_1588xN.1610829934_17rn.jpg',
                'stock': 22,
                'category': categories['Others'],
                'product_type': 'Cube Beads',
                'origin': 'Madagascar',
                'size': '6mm - 8mm',
                'treatment': 'Natural',
            },
        ]
        
        created_count = 0
        for product_data in products_data:
            product, created = Product.objects.get_or_create(
                slug=product_data['slug'],
                defaults=product_data
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'Created product: {product.name}'))
            else:
                self.stdout.write(f'Product already exists: {product.name}')
        
        self.stdout.write(self.style.SUCCESS(f'\nSuccessfully loaded {created_count} new products!'))
        self.stdout.write(self.style.SUCCESS(f'Total products in database: {Product.objects.count()}'))
